insert into states_master  values (1,'AL','Alabama');
insert into states_master  values (2,'AK','Alaska');
insert into states_master  values (3,'AS','American Samoa');
insert into states_master  values (4,'AZ','Arizona');
insert into states_master  values (5,'AR','Arkansas');
insert into states_master  values (6,'CA','California');
insert into states_master  values (7,'CO','Colorado');
insert into states_master  values (8,'CT','Connecticut');
insert into states_master  values (9,'DE','Delaware');
insert into states_master  values (10,'DC','District of Columbia');
insert into states_master  values (11,'FM','Federated states_masters of Micronesia');
insert into states_master  values (12,'FL','Florida');
insert into states_master  values (13,'GA','Georgia');
insert into states_master  values (14,'GU','Guam');
insert into states_master  values (15,'HI','Hawaii');
insert into states_master  values (16,'ID','Idaho');
insert into states_master  values (17,'IL','Illinois');
insert into states_master  values (18,'IN','Indiana');
insert into states_master  values (18,'IA','Iowa');
insert into states_master  values (19,'KS','Kansas');
insert into states_master  values (20,'KY','Kentucky');
insert into states_master  values (21,'LA','Louisiana');
insert into states_master  values (22,'ME','Maine');
insert into states_master  values (23,'MH','Marshall Islands');
insert into states_master  values (24,'MD','Maryland');
insert into states_master  values (25,'MA','Massachusetts');
insert into states_master  values (26,'MI','Michigan');
insert into states_master  values (27,'MN','Minnesota');
insert into states_master  values (28,'MS','Mississippi');
insert into states_master  values (29,'MO','Missouri');
insert into states_master  values (30,'MT','Montana');
insert into states_master  values (31,'NE','Nebraska');
insert into states_master  values (32,'NV','Nevada');
insert into states_master  values (33,'NH','New Hampshire');
insert into states_master  values (34,'NJ','New Jersey');
insert into states_master  values (35,'NM','New Mexico');
insert into states_master  values (36,'NY','New York');
insert into states_master  values (37,'NC','North Carolina');
insert into states_master  values (38,'ND','North Dakota');
insert into states_master  values (39,'MP','Northern Mariana Islands');
insert into states_master  values (40,'OH','Ohio');
insert into states_master  values (41,'OK','Oklahoma');
insert into states_master  values (42,'OR','Oregon');
insert into states_master  values (43,'PW','Palau');
insert into states_master  values (44,'PA','Pennsylvania');
insert into states_master  values (45,'PR','Puerto Rico');
insert into states_master  values (46,'RI','Rhode Island');
insert into states_master  values (47,'SC','South Carolina');
insert into states_master  values (48,'SD','South Dakota');
insert into states_master  values (49,'TN','Tennessee');
insert into states_master  values (50,'TX','Texas');
insert into states_master  values (51,'UT','Utah');
insert into states_master  values (52,'VT','Vermont');
insert into states_master  values (53,'VI','Virgin Islands');
insert into states_master  values (54,'VA','Virginia');
insert into states_master  values (55,'WA','Washington');
insert into states_master  values (56,'WV','West Virginia');
insert into states_master  values (57,'WI','Wisconsin');
insert into states_master  values (58,'WY','Wyoming');
